### PR TITLE
Fix jest plugin omitting `<rootDir>` for aliases involving parent directories

### LINKED ISSUE #45: Jest plugin does not properly handle modules in parent dir
👋  big fan of this package! Ran into a subtle issue in my (unconventional) repo structure.

## Problem

Consider this highly simplified and somewhat contrived example:

```
.
├── README.md
├── app
│   ├── jest.config.js
│   ├── package.json
│   └── src
│       └── index.test.js
├── jest.config.js
├── jsconfig.json
├── package.json
├── src
│   ├── index.test.js
│   └── utils
│       └── some-util.js
└── yarn.lock
```

The bulk of the code lives in `src`, though there's also an `app` directory which functionally is its own package. However, it _does_ share modules (and aliases) with `src`. Consider this `jsconfig.json`:

```json
{
  "compilerOptions": {
    "paths": {
      "@utils/*": ["./src/utils/*"],
      "@app/*": ["./app/src/*"]
    }
  }
}
```

Both the top-level package and `app` have their own set of tests and corresponding `jest.config.js` files. In the top-level config, I would expect (and do correctly get!) the following `moduleNameMapper` value generated by `alias-hq`:
```js
{
  '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  '^@app/(.*)$': '<rootDir>/app/src/$1'
}
```

Likewise for `app`, I would expect this in its config (`app/jest.config.js`):
```js
{
  '^@utils/(.*)$': '<rootDir>/../src/utils/$1',
  '^@app/(.*)$': '<rootDir>/../app/src/$1'
}
```

However, I instead get this:
```js
{
  '^@utils/(.*)$': 'src/utils/$1',
  '^@app/(.*)$': 'app/src/$1'
}
```

## Root cause

This seems to be due to the Jest plugin's implementation using `path.join`:
https://github.com/davestewart/alias-hq/blob/dfb0446a1af3d8eb2e44cb14ae66a26de7347837/src/plugins/jest/index.js#L16

When `baseUrl` is `..`, `join` removes the `<rootDir>` segment entirely. However, in this case (I think) we _always_ want that to exist. Paths like `<rootDir>/../src/utils/$1` resolve just fine with Jest's parser.

I've created a [reproduction repo](https://github.com/chrissantamaria/alias-hq-bug-parent-dir) matching this described case for easier testing. I also have [a branch up](https://github.com/davestewart/alias-hq/compare/master...chrissantamaria:fix-jest-plugin-baseurl-join) which (from what I can tell) fixes the issue - happy to open a PR if you think this is sufficient.

## Possible misconfiguration

I wasn't entirely sure how to configure `alias-hq` for this sort of situation. I did the following in `app/jest.config.js`:
```js
const {
  get: getModuleAliases,
  config: aliasConfig,
  load: loadAliasConfig,
} = require('alias-hq');
const path = require('path');

loadAliasConfig(path.resolve('../jsconfig.json'));
aliasConfig.baseUrl = '..';

module.exports = {
  roots: ['<rootDir>/src'],
  moduleNameMapper: getModuleAliases('jest'),
};
```

(I think) I had to manually point to `jsconfig.json` since it's not in a standard location relative to this config. I also manually set a `baseUrl` so that paths would be set relative to the parent dir. Still fairly new to this package so please let me know if there's a better / simpler way to configure this!

Happy to clarify any details - thanks!

### PR DESCRIPTION
**Pull request by bjoluc**
This is a follow-up on #45 including the fix proposed by @chrissantamaria and adding tests for it. For the tests, I added an `@alias-hq/*` => `../../src` alias to the demo project which resolves to the `src` directory of the `alias-hq` package. The core and all plugins work as expected with the new alias; only the `jest` plugin failed due to #45 before applying the fix.

EDIT: Needless to say, I checked that jest works with `<rootDir>/../` paths.

Closes #45

### CODE REVIEW

File: cli/services/config.js [hunk 1]
```diff
@@ -72,10 +72,10 @@ function getAliases () {
       }
     })
     .sort(function (a, b) {
-      if (a.absPath === b.absPath) {
+      if (a.relPath === b.relPath) {
         return 0
       }
-      return a.absPath > b.absPath ? -1 : 1
+      return a.relPath > b.relPath ? -1 : 1
     })
```
Comment (bjoluc) [inline cli/services/config.js:79]: I changed this to use `relPath` instead of `absPath` so `../../` would be sorted after `../` regardless of parent directory names (as per `tests/specs/cli/get-aliases.spec.js > cli alias configuration > alias lookups should be in reverse path order`). This shouldn't be breaking, unless maybe folks are using symlinks or defining bloated aliases like `src/../src/...`?

**Comment by davestewart** [comment]
Hello! 

And thanks for the PR.

Sorry I missed this. Managed to find some time to get some releases out, so let me take a look at this over Christmas. 

Cheers,
Dave

File: cli/services/config.js (hunk 1 above)
Comment (davestewart) [reply cli/services/config.js:79]: It's most likely to do with the CLI functionality, but it's a couple of years since I looked at that code so I'd have to dig in and look at what it does to the code again. 

From memory it's basically to ensure that the most specific alias is used when converting source code:

https://github.com/davestewart/alias-hq/blob/main/tests/specs/cli/update-source.spec.js#L82-L85

If that still ran, then we should be OK.

I'll take a look at #45 and consider it all together.

Thanks for doing the brainwork!

Comment (bjoluc) [reply cli/services/config.js:79]: > If that test still passed, then we should be OK.

It does :+1:

**Comment by davestewart** [comment]
Just to let you guys know, I finally have the time to check this out and review things!

My utmost apologies that it's taken this long. Shameful! 😬

**Comment by bjoluc** [comment]
Hey @davestewart, thanks for coming back to this again! No probs at all if it takes longer than expected, we can always directly install from forks on GitHub :slightly_smiling_face:
Let me know if there's anything I can help with!

**Comment by FranciscoKloganB** [comment]
Hey, any ideia when this issue will be merged?

To avoid hacks, I am currently hacking the 'hq.get('jest', { format: 'array' })' with a map((x) => x.replace('<rootDir>')) to include the '../'. So I have used --save-exact, but, hey this ain't the cleanest solution.

**Comment by jbrilhante-yogi** [comment]
Hey @davestewart ! I just noticed this bug. It prevents me from using relative paths in my monorepo if I want Jest to work with alias-hq. Is there anything I can do to help with this pull request?

**Comment by davestewart** [comment]
I think I'll just merge this. It sounds like there has been enough testing on it by people using it, and I'm just getting in the way.

Stand by.

**Comment by bjoluc** [comment]
@davestewart In the light of your [review comment above](https://github.com/davestewart/alias-hq/pull/57#discussion_r1041571506), I'm fully confident of this PR, so no obligations from my end!

**Comment by davestewart** [comment]
I've merged everything locally, but have to head out now (on holiday in Malta! 🌞) so will complete when I get in later 👋

**Comment by davestewart** [comment]
I've merged everything locally, but have to head out now (on holiday in Malta! 🌞) so will complete when I get in later 👋

**Comment by bjoluc** [comment]
Great to hear, enjoy your holiday and don't forget to use sunscreen :zany_face:

**Review by davestewart — APPROVED** [review]
Accepted with ❤️ in Malta ☀️ !

**Comment by davestewart** [comment]
OK, published to NPM!

https://www.npmjs.com/package/alias-hq

Thanks again for the PR and sorry it took such a shockingly long time to attend to 🙏

**Comment by bjoluc** [comment]
Thanks for the merge @davestewart! :pray:
